---
- name: Instalar Apache2 y PHP
  hosts: all
  become: yes  # Esto permite ejecutar tareas como superusuario

  tasks:    
    - name: Instalar git
      apt:
        name: git
        state: present
      become_user: root
      
    - name: Clonar el repositorio de GitHub de Apache Wicket
      git:
        repo: https://github.com/alvaroquiroz/Reloj-php.git
        dest: /home/userubuntu/Desktop/html/
      async: 3000
      poll: 0
      become_user: root

    - name: Instalar Apache (httpd)
      apt:
        name: apache2
        state: present
      become_user: root
    
    - name: PHP
      apt:
        name: php
        state: present
      become_user: root
    
    - name: Instalar git
      apt:
        name: git
        state: present
      become_user: root

- name: Clonar el repositorio
  hosts: all
  become: yes
  tasks:
    - name: Crear carpeta /home/userubuntu/Desktop/htmlbackup
      command: mkdir /home/userubuntu/Desktop/htmlbackup
      become_user: root
    
    - name: Mover /var/www/html/ /home/userubuntu/Desktop/htmlbackup/
      command: mv /var/www/html/ /home/userubuntu/Desktop/htmlbackup/
      become_user: root
    
    - name: Mover contenido de /home/userubuntu/Desktop/html/ a /var/www/
      #command: mv /home/userubuntu/Desktop/repo/ /var/www/html/
      command: mv /home/userubuntu/Desktop/html/ /var/www/
      #async: 0
      #poll: 0
      become_user: root

- name: Reiniciar Apache
  hosts: all
  become: yes

  tasks:
    - name: Reiniciar Apache2
      service:
        name: apache2
        state: restarted
      become_user: root