---
- name: Desplegar una aplicación en OpenShift
  hosts: all
  gather_facts: no
  tasks:
    - name: Instalar git
      apt:
        name: git
        state: present
      become_user: root
      
    - name: Clonar el repositorio de GitHub de Apache Wicket
      git:
        repo: https://github.com/alvaroquiroz/AnsibleTower.git
        dest: /home/userubuntu/Desktop/templates/
      async: 3000
      poll: 0
      become_user: root

    - name: Descargar oc
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        dest: /tmp/oc.tar.gz
      become_user: root

    - name: Descomprimir oc
      unarchive:
        src: /tmp/oc.tar.gz
        dest: /usr/local/bin
        remote_src: yes
      become: yes
      become_user: root

    - name: Verificar la instalación de oc
      command: oc version
      ignore_errors: yes
      become_user: root
    
    - name: Actualizar el archivo de hosts
      lineinfile:
        path: /etc/hosts  # Ruta al archivo de hosts en tu sistema
        line: "{{ item.ip }} {{ item.host }}"
        state: present
      with_items:
        - { ip: '52.177.22.54', host: 'console-openshift-console.apps.stracongroupdemo.local' }
        - { ip: '52.177.22.54', host: 'oauth-openshift.apps.stracongroupdemo.local' }
        - { ip: '52.177.22.54', host: 'alertmanager-main-openshift-monitoring.apps.stracongroupdemo.local' }
        - { ip: '52.177.22.54', host: 'boutique-route-boutique.apps.stracongroupdemo.local' }
        - { ip: '40.70.30.118', host: 'api.stracongroupdemo.local' }
      become_user: root


    - name: Extraer el cliente oc
      ansible.builtin.unarchive:
        src: /tmp/oc.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/oc
      become: yes
      when: not ("oc" in ansible_play_hosts_all)
      become_user: root

    - name: Autenticarse en el clúster de OpenShift
      command: oc login -u kubeadmin -p vqit5-uVq55-KM5XD-qs7hJ https://api.stracongroupdemo.local:6443 --insecure-skip-tls-verify
      ignore_errors: yes
      register: oc_login
      environment:
        KUBECONFIG: /home/userubuntu/Desktop/openshift/token
      become_user: root

    - name: Crear o seleccionar el proyecto (namespace) desde archivo YAML
      command: oc apply -f /home/userubuntu/Desktop/templates/filedemo.yaml
      when: "oc_login.rc == 0"
      environment:
        KUBECONFIG: /home/userubuntu/Desktop/openshift/token
      become_user: root