---
- name: Desplegar Apache en todos los servidores
  hosts: all
  become: yes
  tasks:
    - name: Actualizar la caché de paquetes
      apt:
        update_cache: yes

    - name: Instalar Apache (httpd)
      apt:
        name: apache2
        state: present

    - name: Iniciar el servicio Apache
      service:
        name: apache2
        state: started
        enabled: yes
