---
- name: Instalar Apache2 y PHP
  hosts: all
  become: yes  # Esto permite ejecutar tareas como superusuario

  tasks:    
    - name: Instalar Apache (httpd)
      apt:
        name: apache2
        state: present
      become_user: root
    
    - name: PHP
      apt:
        name: php
        state: present
      become_user: root
    
    - name: Instalar git
      apt:
        name: git
        state: present
      become_user: root

- name: Clonar el repositorio de GitHub de Apache Wicket
  hosts: your_server
  become: yes

  tasks:
    - name: Clonar el repositorio de GitHub
      git:
        repo: https://github.com/alvaroquiroz/Reloj-php.git
        dest: /tmp/php
      become_user: root
      async: 600  # Aumenta el tiempo de espera si es necesario (10 minutos)
      poll: 0

- name: Esperar a que termine la clonación del repositorio
  hosts: your_server
  async_status:
    jid: "{{ ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30  # Ajusta según el tiempo de espera necesario
  delay: 10  # Intervalo de comprobación
  become_user: root

- name: Mover contenido de /tmp/php a /var/www/html
  hosts: your_server
  become: yes

  tasks:
    - name: Mover contenido de /tmp/php a /var/www/html
      command: mv /tmp/php/* /var/www/html/
      async: 0
      poll: 0
      become_user: root

    - name: Cambiar el nombre de index.html a index.html.txt
      command: mv /var/www/html/index.html /var/www/html/index.html.txt
      become_user: root

- name: Reiniciar Apache
  hosts: all
  become: yes

  tasks:
    - name: Reiniciar Apache2
      service:
        name: apache2
        state: restarted
      become_user: root