---
- name: Instalar Apache2 y PHP
  hosts: all
  become: yes  # Esto permite ejecutar tareas como superusuario

  tasks:    
    - name: Instalar Apache (httpd)
      apt:
        name: apache2
        state: present
      become_user: root
    
    - name: PHP
      apt:
        name: php
        state: present
      become_user: root
    
    - name: Instalar git
      apt:
        name: git
        state: present
      become_user: root

- name: Clonar el repositorio
  hosts: all
  become: yes

  tasks:
    - name: Clonar el repositorio de GitHub
      git:
        repo: https://github.com/alvaroquiroz/Reloj-php.git
        dest: /var/www/html  # Carpeta donde se clonará el repositorio
      become_user: root
  
  tasks:
    - name: Eliminar index.html
      file:
        path: /var/www/html/index.html
        state: absent
      ignore_errors: yes  # Ignora errores si el archivo no existe
      become_user: root

- name: Reiniciar Apache
  hosts: all
  become: yes

  tasks:
    - name: Reiniciar Apache2
      service:
        name: apache2
        state: restarted
      become_user: root